# Generated by Django 2.2.5 on 2020-02-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='topic',
            new_name='Bears',
        ),
    ]
