# Generated by Django 2.2.5 on 2020-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0002_auto_20200224_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=264, unique=True)),
                ('Last_name', models.CharField(max_length=264, unique=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
