# Generated by Django 2.2.5 on 2020-03-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.CharField(choices=[('FirstWood', 'First Wood'), ('LumberExport', 'Lumber Export'), ('JackInTheBox', 'Jack In The Box'), ('BigWood Inc.', 'Big Wood Inc.'), ('', 'other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
