# Generated by Django 2.2.5 on 2020-03-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketManager', '0004_auto_20200312_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status1',
            new_name='status',
        ),
    ]
